### ISSUE TITLE
每次查询都会出现warning

### ISSUE THREAD

**Issue by YipSzeho** [noneplugin/nonebot-plugin-ddcheck#1]
每次查询都会提示 
[WARNING] nonebot_plugin_ddcheck | Error in get_medals(273198648): 'data'

**Comment by MeetWq** [comment]
如果没有添加B站cookie的话查不到牌子，这个warning就是牌子查询失败

**Comment by YipSzeho** [comment]
谢谢大佬解答٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ
