### ISSUE TITLE
查询失败 cookie已经配置

### ISSUE THREAD

**Issue by Arturia169** [noneplugin/nonebot-plugin-ddcheck#10]
![image](https://user-images.githubusercontent.com/69199123/169457484-02c90ee6-ff7d-486f-b7d7-d2096709e4d1.png)
![image](https://user-images.githubusercontent.com/69199123/169457550-7a6270ad-61aa-4902-b58b-f48a63a4fb0e.png)

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/169457883-5ba9abe7-b751-43c6-ae37-79f842a8dd97.png)
后台的信息

**Comment by MeetWq** [comment]
感觉是网络问题，建议多试几次

**Comment by Arturia169** [comment]
我的服务器部署在国外的会不会是这个原因

**Comment by Arturia169** [comment]
![{_G8EY9J5Z@7X9T3YGM%S)H](https://user-images.githubusercontent.com/69199123/169467724-2bbb2167-8b86-4ccc-87cf-6fb5e463e0db.png)
连接这个api超时了 可能是这个原图

**Comment by MeetWq** [comment]
是api的返回有问题，试试新版本

**Comment by Arturia169** [comment]
新版本怎么获取呢

**Comment by MeetWq** [comment]
```
nb plugin update nonebot_plugin_ddcheck
```
或者
```
pip install --upgrade nonebot_plugin_ddcheck
```
或者
```
poetry update nonebot_plugin_ddcheck
```

**Comment by Arturia169** [comment]
好的

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/169484346-d7bf5238-edde-4cd2-9ba3-1e6aadb2df25.png)
已解决 更新插件
