### ISSUE TITLE
报错，好像是解析有问题

### ISSUE THREAD

**Issue by sakamataz** [noneplugin/nonebot-plugin-ddcheck#16]
![image](https://user-images.githubusercontent.com/44469959/176931493-0058d368-a044-4a76-9faa-e41c623ef33e.png)

**Comment by zjp-shadow** [comment]
+1 我也遇到了这个问题

**Comment by MeetWq** [comment]
https://github.com/noneplugin/nonebot-plugin-ddcheck/commit/3881d0e90468381d9315f66e2268e652c027c80c
