### ISSUE TITLE
查成分失败

### ISSUE THREAD

**Issue by yoiyami96** [noneplugin/nonebot-plugin-ddcheck#17]
查成分不显示管人关注名单了，全部为0，日志无报错，换旧版插件也不行<img src = 'https://s3.bmp.ovh/imgs/2022/07/16/a826eccffaa32637.png' />
<img src = 'https://s3.bmp.ovh/imgs/2022/07/16/6a41a6943c0a6f0c.png' />

**Comment by MeetWq** [comment]
你看一下有没有设置关注列表不可见，试试没设置不可见的uid看行不行

**Comment by yoiyami96** [comment]
> 你看一下有没有设置关注列表不可见，试试没设置不可见的uid看行不行

设置关注列表可见后能正常使用了，现在关注列表不可见就没法查成分了吗，以前还能用😥

**Comment by MeetWq** [comment]
好像确实查不了了，不知道还有没有别的接口

**Comment by MeetWq** [comment]
我等下加个“关注列表可能不可见”的提示
