### ISSUE TITLE
【报错】出错了...

### ISSUE THREAD

**Issue by Agnes4m** [noneplugin/nonebot-plugin-ddcheck#18]
python3.9.13 nonebot2.0.0b5
机器人回答：出错了，请稍后再试

下面是终端
```
08-25 12:23:48 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_ddcheck, type=message, priority=12, temp=False>
08-25 12:23:48 [WARNING] nonebot_plugin_ddcheck | Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_ddcheck/__init__.py", line 39, in _
    res = await get_reply(text)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_ddcheck/data_source.py", line 156, in get_reply
    uid = await get_uid_by_name(name)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_ddcheck/data_source.py", line 94, in get_uid_by_name    for user in result["data"]["result"]:
TypeError: 'NoneType' object is not subscriptable

08-25 12:23:48 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_ddcheck, type=message, priority=12, temp=False> running complete
```

**Comment by Agnes4m** [comment]
已更新0.1.12
查成分依然有如上问题，但是数字可以查
![image](https://user-images.githubusercontent.com/70925546/187338750-d39a52b5-780c-4c0a-a3d2-22d7bc38f864.png)

**Comment by MeetWq** [comment]
由于b站api变动，现在搜索用户名也需要cookie了，检查一下cookie配置是否正确

**Comment by balh55y** [comment]
![image](https://user-images.githubusercontent.com/85926883/187365360-4309b462-7fda-4ca7-b36b-b5b24db854cb.png)
```
08-30 14:24:12 [SUCCESS] nonebot | ONEBOT V11 2889211163 | [message.private.friend]: Message 1503658492 from 2779375323 "查成分 2642708"
08-30 14:24:13 [INFO] nonebot | Event will be handled by <Matcher from src.nonebot_plugin.nonebot_plugin_ddcheck, type=message, priority=12, temp=False>
bilibilicode:0aefd36b%2C1676286367%2C8ccf7%2A81
08-30 14:24:13 [WARNING] src | Error in get_medals(2642708): 'data'
08-30 14:24:13 [WARNING] src | Traceback (most recent call last):
  File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/__init__.py", line 39, in _
    res = await get_reply(text)
  File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/data_source.py", line 194, in get_reply
    content = await template.render_async(info=result)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1324, in render_async
    return self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1321, in <listcomp>
    [n async for n in self.root_render_func(ctx)]  # type: ignore
  File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/template/info.html", line 163, in top-level template code
    {% for i in range(0, (info['vtbs'] | length), info['p']) %}
TypeError: 'Undefined' object cannot be interpreted as an integer

08-30 14:24:13 [INFO] nonebot | Matcher <Matcher from src.nonebot_plugin.nonebot_plugin_ddcheck, type=message, priority=12, temp=False> running complete
```
![image](https://user-images.githubusercontent.com/85926883/187365834-00127d0d-a25e-4021-b9bd-4f5a1ec7e2d9.png)
我是两种都不行

**Comment by MeetWq** [comment]
cookie要填写完整
```
bilibili_cookie="SESSDATA=xxx;"
```
这种形式

**Comment by balh55y** [comment]
> 饼干要填写完整
> 
> ```
> bilibili_cookie="SESSDATA=xxx;"
> ```
> 
> 形式

```
08-30 15:14:18 [SUCCESS] nonebot | ONEBOT V11 2889211163 | [message.private.friend]: Message -920707987 from 2779375323 "查成分 2642708"
08-30 15:14:19 [INFO] nonebot | Event will be handled by <Matcher from src.nonebot_plugin.nonebot_plugin_ddcheck, type=message, priority=12, temp=False>
bilibilicode:SESSDATA=0aefd36b%2C1676286367%2C8ccf7%2A81;
08-30 15:14:19 [WARNING] src | Traceback (most recent call last):
  File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/__init__.py", line 39, in _
    res = await get_reply(text)
  File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/data_source.py", line 194, in get_reply
    content = await template.render_async(info=result)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1324, in render_async
    return self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1321, in <listcomp>
    [n async for n in self.root_render_func(ctx)]  # type: ignore
  File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/template/info.html", line 163, in top-level template code
    {% for i in range(0, (info['vtbs'] | length), info['p']) %}
TypeError: 'Undefined' object cannot be interpreted as an integer

08-30 15:14:19 [INFO] nonebot | Matcher <Matcher from src.nonebot_plugin.nonebot_plugin_ddcheck, type=message, priority=12, temp=False> running complete
```

**Comment by balh55y** [comment]
> > 饼干要填写完整
> > ```
> > bilibili_cookie="SESSDATA=xxx;"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 形式
> 
> ```
> 08-30 15:14:18 [SUCCESS] nonebot | ONEBOT V11 2889211163 | [message.private.friend]: Message -920707987 from 2779375323 "查成分 2642708"
> 08-30 15:14:19 [INFO] nonebot | Event will be handled by <Matcher from src.nonebot_plugin.nonebot_plugin_ddcheck, type=message, priority=12, temp=False>
> bilibilicode:SESSDATA=0aefd36b%2C1676286367%2C8ccf7%2A81;
> 08-30 15:14:19 [WARNING] src | Traceback (most recent call last):
>   File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/__init__.py", line 39, in _
>     res = await get_reply(text)
>   File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/data_source.py", line 194, in get_reply
>     content = await template.render_async(info=result)
>   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1324, in render_async
>     return self.environment.handle_exception()
>   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
>     raise rewrite_traceback_stack(source=source)
>   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1321, in <listcomp>
>     [n async for n in self.root_render_func(ctx)]  # type: ignore
>   File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/template/info.html", line 163, in top-level template code
>     {% for i in range(0, (info['vtbs'] | length), info['p']) %}
> TypeError: 'Undefined' object cannot be interpreted as an integer
> 
> 08-30 15:14:19 [INFO] nonebot | Matcher <Matcher from src.nonebot_plugin.nonebot_plugin_ddcheck, type=message, priority=12, temp=False> running complete
> ```

我重新git了一份传上去,好使了o(╥﹏╥)o

**Comment by kanoucy** [comment]
> > > 饼干要填写完整
> > > ```
> > > bilibili_cookie="SESSDATA=xxx;"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 形式
> > 
> > 
> > ```
> > 08-30 15:14:18 [SUCCESS] nonebot | ONEBOT V11 2889211163 | [message.private.friend]: Message -920707987 from 2779375323 "查成分 2642708"
> > 08-30 15:14:19 [INFO] nonebot | Event will be handled by <Matcher from src.nonebot_plugin.nonebot_plugin_ddcheck, type=message, priority=12, temp=False>
> > bilibilicode:SESSDATA=0aefd36b%2C1676286367%2C8ccf7%2A81;
> > 08-30 15:14:19 [WARNING] src | Traceback (most recent call last):
> >   File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/__init__.py", line 39, in _
> >     res = await get_reply(text)
> >   File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/data_source.py", line 194, in get_reply
> >     content = await template.render_async(info=result)
> >   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1324, in render_async
> >     return self.environment.handle_exception()
> >   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
> >     raise rewrite_traceback_stack(source=source)
> >   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1321, in <listcomp>
> >     [n async for n in self.root_render_func(ctx)]  # type: ignore
> >   File "/root/qqbot/Liteyuki/src/nonebot_plugin/nonebot_plugin_ddcheck/template/info.html", line 163, in top-level template code
> >     {% for i in range(0, (info['vtbs'] | length), info['p']) %}
> > TypeError: 'Undefined' object cannot be interpreted as an integer
> > 
> > 08-30 15:14:19 [INFO] nonebot | Matcher <Matcher from src.nonebot_plugin.nonebot_plugin_ddcheck, type=message, priority=12, temp=False> running complete
> > ```
> 
> 我重新git了一份传上去,好使了o(╥﹏╥)o

请问如何解决的呀
