### ISSUE TITLE
输入查询指令后报错

### ISSUE THREAD

**Issue by kanoucy** [noneplugin/nonebot-plugin-ddcheck#19]
设置了SESSDATA后，只能通过UID查询，通过用户名查询就会提示 出错了，请稍后再试
![image](https://user-images.githubusercontent.com/112235434/188675584-4d992b24-e19c-43a3-9cdf-57e8606e2133.png)

**Comment by ElainaFanBoy** [comment]
我也遇到了这个情况0.0

**Comment by MeetWq** [comment]
更新版本，正确设置cookie，应该是没问题的，还有问题可以在这里讨论
#18
