### ISSUE TITLE
请问下配置中的cookie

### ISSUE THREAD

**Issue by ZeroBloodedge** [noneplugin/nonebot-plugin-ddcheck#2]
请问下配置中需要的cookie，是哪一条呀。。

**Comment by MeetWq** [comment]
哪一条是什么意思？

**Comment by ZeroBloodedge** [comment]
就是不知道填写哪一个
我把bilibili.com的cookie里的bili_jct这一条填进去了但是好像并没有用，牌子获取还是会报失败，我就想是不是搞错了。。

**Comment by MeetWq** [comment]
你把整个cookie的字符串填上去就行
