### ISSUE TITLE
一些意见

### ISSUE THREAD

**Issue by Nenot233** [noneplugin/nonebot-plugin-ddcheck#20]
bh.ayud.top/bili/bilicfsql.php
这个网站每天会自动更新拉取VTB用户

**Comment by MeetWq** [comment]
这个接口是比 [vtbs.moe](https://vtbs.moe/) 更全吗？

**Comment by Nenot233** [comment]
是的每天都会更新

**Comment by MeetWq** [comment]
这接口怎么爬的，有的uid居然是小数。。。
![Snipaste_2022-10-03_17-04-26](https://user-images.githubusercontent.com/33149974/193540276-89ffb312-d588-4843-9243-0ac1b845ddf7.png)

**Comment by Nenot233** [comment]
好了，长UID不加限制 PHP自动转科学计数法

**Comment by Nenot233** [comment]
这个排序，是否可以以牌子等级优先排序？

**Comment by YujioNako** [comment]
这个接口似乎已经作废了

**Comment by Nenot233** [comment]
> 这个接口似乎已经作废了

因为作者已经换接口了
