### ISSUE TITLE
改编请求

### ISSUE THREAD

**Issue by YujioNako** [noneplugin/nonebot-plugin-ddcheck#24]
我想请求将本插件改编为能被Yunzai-Bot直接使用的js插件，不知您是否允许？改编后会注明核心代码源自您的项目的

**Comment by MeetWq** [comment]
可以的，注明出处即可

**Comment by YujioNako** [comment]
> 可以的，注明出处即可

link：https://github.com/ldcivan/ddcheck_plugin
