### ISSUE TITLE
获取数据出错

### ISSUE THREAD

**Issue by OnlyblackTea** [noneplugin/nonebot-plugin-ddcheck#28]
环境：Ubuntu 20.04，Nonebot2，go-cqhttp
命令：查成分+id
具体报错如下图
![CAPLC9{@EQ%4O)9}9M1{66U](https://user-images.githubusercontent.com/38585636/220249235-dc551dd3-93ea-49b5-a2ec-e75b19af4b23.png)

**Comment by MeetWq** [comment]
重启一下nonebot
