### ISSUE TITLE
BUG:出错了，请稍后再试

### ISSUE THREAD

**Issue by Agnes4m** [noneplugin/nonebot-plugin-ddcheck#29]
![image](https://user-images.githubusercontent.com/70925546/228714290-645ce502-83d6-4deb-a3cb-1e485abef283.png)
env:
![image](https://user-images.githubusercontent.com/70925546/228716616-2b0831f0-0598-446d-816d-d735e5e5f406.png)

**Comment by MeetWq** [comment]
新版加了 `user-agent`，应该能解决
