### ISSUE TITLE
无法加载牌子的问题

### ISSUE THREAD

**Issue by Agnes4m** [noneplugin/nonebot-plugin-ddcheck#3]
插件正常功能启动，但无法显示牌子，终端显示

[succss] nonebot i ONEoT V11 344524586 | [message.private.friend]: Nessage -2138501333 from 735803792"查成分hanser"
[INFo] nonebot | Event will be handled by TNatcher from nonebot plugin_ddcheck， type-message, priority=12, temp=False>**[WARNING] nonebot plugin_adcheck | Error in get_medals(11073): data'**
[INFo] nonebot |vatcher 《Natcher from nonebot plugin_dicheck, type=message, priority=12, temp=False> running complete

dev.xx文件已写入cookie，是不是少了文件？

**Comment by Agnes4m** [comment]
![QQ截图20220411160745](https://user-images.githubusercontent.com/70925546/162692835-e47d2d65-4bc1-4d59-8a51-28d863afbb2d.png)

**Comment by MeetWq** [comment]
感觉还是cookie的问题，你再检查一下？

**Comment by Agnes4m** [comment]
这个格式应该没有问题吧，我试着把“”去掉也没有正常运行

![QQ截图20220411194931](https://user-images.githubusercontent.com/70925546/162733531-489c5802-4af3-4e0b-a575-6794629ed8ac.png)

**Comment by MeetWq** [comment]
看上去没问题，重启过没？

**Comment by Agnes4m** [comment]
重启过了，加载出来的仍然是没有牌子的图片。
甚至电脑整体重启也试过了，此功能会和其他插件不会有冲突吧。

**Comment by Agnes4m** [comment]
![QQ截图20220411201141](https://user-images.githubusercontent.com/70925546/162736820-51681227-be42-44e7-9e4b-a4f7f16f5ab8.png)
这是操作实际效果，麻烦大佬看看是哪里出了问题

**Comment by MeetWq** [comment]
我不确定 .env 里等号两边能不能加空格
你把空格删了试试

**Comment by Agnes4m** [comment]
还是不行，无论加上还是没有空格或者“”都无法正常启动，
![QQ截图20220411230120](https://user-images.githubusercontent.com/70925546/162768825-2b90cbbf-7fe9-481e-95e8-9d3047d047f8.png)
想确认下这个路径下没有少文件吧。

**Comment by MeetWq** [comment]
没少

**Comment by Agnes4m** [comment]
感谢大佬我已经解决问题了，问题在于我没获取正确的b站cookie，通常的获取cookie方法并不适用于b站、

**Comment by yoiyami96** [comment]
> b站cookie

你好，能问一下该怎么获取正常的b站cookie吗，我f12获取的那一长串cookie填了也没用

**Comment by MeetWq** [comment]
我用的就是 F12 获取的 cookie，没问题呀
F12 找 www.bilibili.com 里面的 cookie

![Snipaste_2022-04-18_17-54-32.png](https://s2.loli.net/2022/04/18/Bmuy2t7KixE4lGR.png)

**Comment by yoiyami96** [comment]
> 我用的就是 F12 获取的 cookie，没问题呀 F12 找 [www.bilibili.com](http://www.bilibili.com) 里面的 cookie
> 
> ![Snipaste_2022-04-18_17-54-32.png](https://camo.githubusercontent.com/4c4f15c3b50856273d369a3d10cb640a444ac28e8f87380bfdd6bd3cc928a88b/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30342f31382f426d75793274374b697845346c47522e706e67)

感谢解答，回头我再试试，谢谢大佬开发的插件
