### ISSUE TITLE
以用户名查成分报错TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rainyorange** [noneplugin/nonebot-plugin-ddcheck#30]
![image](https://github.com/noneplugin/nonebot-plugin-ddcheck/assets/36807368/afbed1d1-76a7-4917-9b79-025e5e6ade1d)
![image](https://github.com/noneplugin/nonebot-plugin-ddcheck/assets/36807368/60c83be2-6100-47b5-8f59-ba08ff7addf0)

**Comment by rainyorange** [comment]
![image](https://github.com/noneplugin/nonebot-plugin-ddcheck/assets/36807368/991afcb2-2f52-40c7-bfd1-a5848ab7f523)

**Comment by MeetWq** [comment]
更新了，可以试试
