### ISSUE TITLE
一个小请求

### ISSUE THREAD

**Issue by po-lan** [noneplugin/nonebot-plugin-ddcheck#4]
我对你的插件改写了一下
简单说就是适配真寻
希望我可以开源在我自己的GitHub

**Comment by MeetWq** [comment]
你可以fork一下，在fork的基础上改

**Comment by po-lan** [comment]
> 你可以fork一下，在fork的基础上改

好的让我研究一下

**Comment by po-lan** [comment]
讲个笑话 我不会修改

**Comment by po-lan** [comment]
> 讲个笑话 我不会修改

然后一个文件一个文件改的

**Comment by po-lan** [comment]
你看一下，我是新人 玩的不太明白
